// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, mac_address, ip_address, hostname, first_seen, last_seen, is_known
FROM devices
WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.IpAddress,
		&i.Hostname,
		&i.FirstSeen,
		&i.LastSeen,
		&i.IsKnown,
	)
	return i, err
}

const getDeviceByMAC = `-- name: GetDeviceByMAC :one
SELECT id, mac_address, ip_address, hostname, first_seen, last_seen, is_known
FROM devices
WHERE mac_address = $1
`

func (q *Queries) GetDeviceByMAC(ctx context.Context, macAddress string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByMAC, macAddress)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.IpAddress,
		&i.Hostname,
		&i.FirstSeen,
		&i.LastSeen,
		&i.IsKnown,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, mac_address, ip_address, hostname, first_seen, last_seen, is_known
FROM devices
ORDER BY last_seen DESC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.MacAddress,
			&i.IpAddress,
			&i.Hostname,
			&i.FirstSeen,
			&i.LastSeen,
			&i.IsKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnknownDevices = `-- name: ListUnknownDevices :many
SELECT id, mac_address, ip_address, hostname, first_seen, last_seen, is_known
FROM devices
WHERE is_known = FALSE
ORDER BY last_seen DESC
`

func (q *Queries) ListUnknownDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listUnknownDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.MacAddress,
			&i.IpAddress,
			&i.Hostname,
			&i.FirstSeen,
			&i.LastSeen,
			&i.IsKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceKnown = `-- name: MarkDeviceKnown :one
UPDATE devices
SET is_known = TRUE
WHERE mac_address = $1
RETURNING id, mac_address, ip_address, hostname, first_seen, last_seen, is_known
`

func (q *Queries) MarkDeviceKnown(ctx context.Context, macAddress string) (Device, error) {
	row := q.db.QueryRow(ctx, markDeviceKnown, macAddress)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.IpAddress,
		&i.Hostname,
		&i.FirstSeen,
		&i.LastSeen,
		&i.IsKnown,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (id, mac_address, ip_address, hostname, first_seen, last_seen)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (mac_address)
DO UPDATE SET
    ip_address = EXCLUDED.ip_address,
    hostname   = COALESCE(EXCLUDED.hostname, devices.hostname),
    last_seen  = NOW()
RETURNING id, mac_address, ip_address, hostname, first_seen, last_seen, is_known
`

type UpsertDeviceParams struct {
	ID         uuid.UUID `json:"id"`
	MacAddress string    `json:"mac_address"`
	IpAddress  string    `json:"ip_address"`
	Hostname   *string   `json:"hostname"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.MacAddress,
		arg.IpAddress,
		arg.Hostname,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.IpAddress,
		&i.Hostname,
		&i.FirstSeen,
		&i.LastSeen,
		&i.IsKnown,
	)
	return i, err
}
