// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enforcement_events.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEnforcementEvent = `-- name: CreateEnforcementEvent :one
INSERT INTO enforcement_events (id, device_id, agent_id, action)
VALUES ($1, $2, $3, $4)
RETURNING id, device_id, agent_id, action, created_at
`

type CreateEnforcementEventParams struct {
	ID       uuid.UUID `json:"id"`
	DeviceID uuid.UUID `json:"device_id"`
	AgentID  string    `json:"agent_id"`
	Action   string    `json:"action"`
}

func (q *Queries) CreateEnforcementEvent(ctx context.Context, arg CreateEnforcementEventParams) (EnforcementEvent, error) {
	row := q.db.QueryRow(ctx, createEnforcementEvent,
		arg.ID,
		arg.DeviceID,
		arg.AgentID,
		arg.Action,
	)
	var i EnforcementEvent
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.AgentID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}
