// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID         uuid.UUID `json:"id"`
	MacAddress string    `json:"mac_address"`
	IpAddress  string    `json:"ip_address"`
	Hostname   *string   `json:"hostname"`
	FirstSeen  time.Time `json:"first_seen"`
	LastSeen   time.Time `json:"last_seen"`
	IsKnown    bool      `json:"is_known"`
}
