// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID         pgtype.UUID        `json:"id"`
	MacAddress string             `json:"mac_address"`
	IpAddress  string             `json:"ip_address"`
	Hostname   *string            `json:"hostname"`
	FirstSeen  pgtype.Timestamptz `json:"first_seen"`
	LastSeen   pgtype.Timestamptz `json:"last_seen"`
	IsKnown    bool               `json:"is_known"`
}
